apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pulpito
  namespace: pulpito
spec:
  to:
    kind: Service
    name: pulpito
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
