apiVersion: v1
kind: Service
metadata:
  name: pulpito
  namespace: pulpito
  labels:
    app: pulpito
spec:
  selector:
    app: pulpito
  ports:
    - name: http
      port: 8081
      targetPort: 8081
